name:                Day7
version:             0.1.0.0
github:              "githubuser/Day7"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/Day7#readme>

dependencies:
- base >= 4.7 && < 5
- tasty
- tasty-hunit
- tasty-hspec
- parsec
- parsec-numbers
- containers

library:
  source-dirs: src

executables:
  Day7-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day7
    - containers

tests:
  Day7-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Day7
    - tasty
    - parsec
    - parsec-numbers
    - containers
